### ISSUE TITLE
Make a homepage

### ISSUE THREAD

**Issue by exelotl** [gbadev-org/tonc#1]
The homepage is currently blank. Maybe we should remove `toc.htm` and put the TOC on the homepage along with a short intro?

Alternatively, make `intro.htm` the homepage and move the TOC into a sidebar, which would be accessible from every page.

**Comment by avivace** [comment]
(@JoaoBaptMG We did decide to go for mdbook)

**Comment by avivace** [comment]
I added a very simple foreword. Feel free to PR additional information / modifications: https://github.com/gbadev-org/tonc/commit/2a36d32a83450b6bc5287fcd98617a49936de979
