### ISSUE TITLE
Bit layout diagram / table confusion

### ISSUE THREAD

**Issue by exelotl** [gbadev-org/tonc#34]
In Tonc, the register / bit layout diagrams have an effect on the table numbering, but they don't tend to have a table number displayed on them, which is kind of confusing.

Should we:

a) Keep treating them as tables, with invisible numbers (i.e. do nothing)
b) Keep treating them as tables, and show the numbers.
c) Stop treating them as tables, so all other table numbers in the document will be adjusted accordingly.

**Comment by LunarLambda** [comment]
It would probably be easiest and most consistent to not treat them as tables (I assume this means ignoring them in the xnos preprocessor *unless* they have a matching id attribute?)

**Comment by exelotl** [comment]
Yeah it's easy to solve either way, not a technical problem, just a question of how's best to handle it when encountered during md porting, since these numbering discrepancies are present in the original Tonc text.

I'm also in favour of just not treating them as tables (so don't give them a `tbl:` ID, and accept that the tables numbers in the document will change).
