### ISSUE TITLE
Convert sources to Markdown

### ISSUE THREAD

**Issue by exelotl** [gbadev-org/tonc#4]
See [Converting Pages to Markdown](https://github.com/gbadev-org/tonc#converting-pages-to-markdown) in the readme for step-by-step instructions.

Progress:

- [x] intro (Introduction to Tonc)

Part 2
- [x] #25
- [x] #2 
- [x] first (My First GBA Demo)
- [x] #10 
- [x] #11 
- [x] #18
- [x] #19
- [x] #20
- [x] #21

Part 3
- [x] #22
- [x] #30
- [x] #31
- [x] #32
- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #39

Part 4
- [x] #44
- [x] #45
- [x] #46
- [x] #61
- [x] #62
- [x] #63

Part 5
- [x] #50
- [x] #49
- [x] #48
- [x] #66
- [x] #65
- [x] #47
- [x] #64

**Comment by LunarLambda** [comment]
I'll give hardware a go

**Comment by gwilymk** [comment]
I'll do the affine chapter (jumping in the middle to prevent potential duplicate work)
