### ISSUE TITLE
Wrong Linux environment variable

### ISSUE THREAD

**Issue by gresskar** [gbadev-org/tonc#57]
`$(DEVKITPRO)/examples/gba/template` should be `${DEVKITPRO}/examples/gba/template`  in /tonc/setup.html

**Comment by LunarLambda** [comment]
there's also one for `$(DEVKITPRO)/msys/bin`. While this syntax is valid in a Makefile, from context it doesn't look like that's what's being talked about. For shells, `$DEVKITPRO` or `${DEVKITPRO}` are indeed correct

**Comment by exelotl** [comment]
Thanks for the heads up! I started redoing the setup chapter a few weeks ago but life got in the way, I'll get back to it soon and make sure it doesn't have this issue :+1:

**Comment by avivace** [comment]
@exelotl is this fixed?

**Comment by exelotl** [comment]
Yep!
