### ISSUE TITLE
Deku's sound tutorial is still online

### ISSUE THREAD

**Issue by ketsuban** [gbadev-org/tonc#59]
The introduction links to Deku's main site, which has been a "now found at" link to a dead hosting service for a while, but [the sound tutorial itself is still online](https://deku.gbadev.org/program/sound1.html). The introduction should probably link to that (or perhaps a Markdown-ised version of it, so people don't have to stare at the background colour #C09973 for any longer than necessary) rather than just label the link "b0rked".

**Comment by copyrat90** [comment]
This should be a great alternative link:
HTML: https://stuij.github.io/deku-sound-tutorial/
Repo: https://github.com/stuij/deku-sound-tutorial

**Comment by avivace** [comment]
> This should be a great alternative link: HTML: https://stuij.github.io/deku-sound-tutorial/ Repo: https://github.com/stuij/deku-sound-tutorial

Yep, we can use those

**Comment by avivace** [comment]
Done in https://github.com/gbadev-org/tonc/commit/d9011f82e9970fcb8f999df0201686fb466ecf3c
