### ISSUE TITLE
Replace math expressions with LaTeX

### ISSUE THREAD

**Issue by exelotl** [gbadev-org/tonc#7]
Tonc uses HTML formatting tricks to make things look like mathematical expressions.

Ideally we'll clean this up with a plugin which generates SVGs from LaTeX. 

The path of least resistance would be to use MathJax but I'm not a fan of relying on JavaScript plus a third-party service just to render some equations.

**Comment by avivace** [comment]
Let's go with [MathML](https://en.wikipedia.org/wiki/MathML)
 See an example from Pan Docs:

Rendered: https://gbdev.io/pandocs/Audio_Registers.html
Source: https://raw.githubusercontent.com/gbdev/pandocs/master/src/Audio_Registers.md
